server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zhanghao
    password: mima
    url: jdbc:mysql://localhost:3306/test?character-set=utf-8
  activiti:
    database-schema-update: true
    history-level: audit
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
#logging:
#  level: info
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql